runtime: python312
entrypoint: streamlit run web/main.py --server.port $PORT --server.headless true

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5

env_variables:
  STREAMLIT_SERVER_PORT: $PORT
  STREAMLIT_SERVER_HEADLESS: true
  GOOGLE_APPLICATION_CREDENTIALS: $GCP_CREDENTIALS
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASS: $POSTGRES_PASS

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto